version: '3.9'

services:
  # react:
  #   image: node:16.13.2
  #   container_name: react
  #   ports:
  #     - "3001:3000"
  #   volumes:
  #     - ./node_volume/:/opt/node_volume/
  #   command: bash -c "cd /opt/node_volume/ceep && npm start"

  controlador:
    container_name: controlador
    build:
      dockerfile: build/python/Dockerfile
      context: .
      target: python_controlador
    networks:
      - backend
    depends_on:
      - "cadastrador"
      - "avaliador"
  
  cadastrador:
    container_name: cadastrador
    build:
      dockerfile: build/python/Dockerfile
      context: .
      target: python_cadastrador
    networks:
      - backend
    depends_on:
      - "bancodedados"

  avaliador:
    container_name: avaliador
    build:
      dockerfile: build/python/Dockerfile
      context: .
      target: python_avaliador
    networks:
      - backend
    depends_on:
      - "bancodedados"
  
  bancodedados:
    container_name: bancodedados
    build:
      dockerfile: build/mysql/Dockerfile
      context: .
    environment:
      - MYSQL_ROOT_HOST='%'
    networks:
      - backend
    volumes:
      - bancodedados:/var/lib/mysql

volumes:
  bancodedados:

networks:
  backend:
    