version: '2'

services:
  node:
    image: node:16.13.2
    container_name: node_builder
    # ports:
    #   - "3001:3000"
    volumes:
      - ./node_volume/:/opt/node_volume/
    command: bash -c "cd /opt/node_volume/ceep && npm install --silent"